### ISSUE TITLE
Conflict with already longstanding ID of Nucleus Plugin.

### ISSUE THREAD

**Issue by GeorgeWL** [pauljoda/Nucleus#3]
The modpack Rustic Waters (server files) has the mod Nucleus (Nucleus-1.12.2-1.0-B15.jar) in it. 

Nucleus is one of the main plugins for Sponge servers (like ours). 

Having both the mod (which has used the mod ID since 2017) and plugin (which has used the mod ID since 2015) on the server causes the server to see duplicate jars so we're forced to disable one. 

The plugin was not an option so we disabled the mod version. This sadly caused a crash. The mod AssistedProgression caused crashes when we removed Nucleus. 

So the server crashes on startup when AssistedProgression loads. 

This however doesn't happen when we use the mod version of Nucleus instead of the plugin version. 

The mod version however doesn't support any of our ranks, features, warps, kits etc so it is an instant no for us. 

We could disable AssistedProgression but it looks to me like an important mod. 

Crashlog: https://pastebin.com/gRyt7rZg

AssistedProgression: https://www.curseforge.com/minecraft/mc-mods/assisted-progression

**Comment by pauljoda** [comment]
We will be using nucleus_teambr going forward in new versions, thank you for the information

**Comment by Brend-Smits** [comment]
Could this change also be backported to a 1.12.2 version please? This would allow us to push some more pack updates to fix this issue. 
I can fix it myself, but clients will also require the correct mod id or else they won't be able to join the server.

Thank you in advance!
